"""Initial tables

Revision ID: 3707d49db3c9
Revises: 
Create Date: 2026-09-18 12:24:43.492597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3707d49db3c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('account_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('skintwins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('body_location', sa.String(length=100), nullable=False),
    sa.Column('body_side', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('baseline_capture_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_capture_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skintwins_public_id'), 'skintwins', ['public_id'], unique=True)
    op.create_index(op.f('ix_skintwins_user_id'), 'skintwins', ['user_id'], unique=False)
    op.create_table('captures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skintwin_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('image_object_key', sa.String(length=500), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body_location', sa.String(length=100), nullable=True),
    sa.Column('device_metadata', sa.Text(), nullable=True),
    sa.Column('quality_status', sa.String(length=50), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('reference_scale_available', sa.Boolean(), nullable=False),
    sa.Column('measurement_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['skintwin_id'], ['skintwins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captures_skintwin_id'), 'captures', ['skintwin_id'], unique=False)
    op.create_index(op.f('ix_captures_user_id'), 'captures', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skintwin_id', sa.String(length=36), nullable=False),
    sa.Column('capture_id', sa.String(length=36), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('symptoms', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skintwin_id'], ['skintwins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_skintwin_id'), 'notes', ['skintwin_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('sharing_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skintwin_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_identifier', sa.String(length=255), nullable=False),
    sa.Column('permission_level', sa.String(length=50), nullable=False),
    sa.Column('expiry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skintwin_id'], ['skintwins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharing_permissions_skintwin_id'), 'sharing_permissions', ['skintwin_id'], unique=False)
    op.create_index(op.f('ix_sharing_permissions_user_id'), 'sharing_permissions', ['user_id'], unique=False)
    op.create_table('comparisons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skintwin_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('earlier_capture_id', sa.String(length=36), nullable=False),
    sa.Column('latest_capture_id', sa.String(length=36), nullable=False),
    sa.Column('comparison_status', sa.String(length=50), nullable=False),
    sa.Column('alignment_status', sa.String(length=50), nullable=False),
    sa.Column('reliability_status', sa.String(length=50), nullable=False),
    sa.Column('observable_change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['earlier_capture_id'], ['captures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['latest_capture_id'], ['captures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skintwin_id'], ['skintwins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparisons_skintwin_id'), 'comparisons', ['skintwin_id'], unique=False)
    op.create_index(op.f('ix_comparisons_user_id'), 'comparisons', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comparisons_user_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_skintwin_id'), table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index(op.f('ix_sharing_permissions_user_id'), table_name='sharing_permissions')
    op.drop_index(op.f('ix_sharing_permissions_skintwin_id'), table_name='sharing_permissions')
    op.drop_table('sharing_permissions')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_skintwin_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_captures_user_id'), table_name='captures')
    op.drop_index(op.f('ix_captures_skintwin_id'), table_name='captures')
    op.drop_table('captures')
    op.drop_index(op.f('ix_skintwins_user_id'), table_name='skintwins')
    op.drop_index(op.f('ix_skintwins_public_id'), table_name='skintwins')
    op.drop_table('skintwins')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
