"""Add milestone 6 alignment medsam measurement and reliability fields

Revision ID: 765be5ecfe7b
Revises: ad4cb0027bd9
Create Date: 2026-09-18 14:03:15.752295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765be5ecfe7b'
down_revision: Union[str, Sequence[str], None] = 'ad4cb0027bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparisons', sa.Column('processing_status', sa.String(length=50), nullable=False))
    op.add_column('comparisons', sa.Column('processing_error_code', sa.String(length=50), nullable=True))
    op.add_column('comparisons', sa.Column('alignment_score', sa.Float(), nullable=True))
    op.add_column('comparisons', sa.Column('match_count', sa.Integer(), nullable=True))
    op.add_column('comparisons', sa.Column('inlier_count', sa.Integer(), nullable=True))
    op.add_column('comparisons', sa.Column('inlier_ratio', sa.Float(), nullable=True))
    op.add_column('comparisons', sa.Column('alignment_method', sa.String(length=50), nullable=True))
    op.add_column('comparisons', sa.Column('alignment_error_code', sa.String(length=50), nullable=True))
    op.add_column('comparisons', sa.Column('localization_status', sa.String(length=50), nullable=False))
    op.add_column('comparisons', sa.Column('localization_confidence', sa.Float(), nullable=True))
    op.add_column('comparisons', sa.Column('segmentation_model', sa.String(length=50), nullable=True))
    op.add_column('comparisons', sa.Column('segmentation_model_version', sa.String(length=50), nullable=True))
    op.add_column('comparisons', sa.Column('segmentation_error_code', sa.String(length=50), nullable=True))
    op.add_column('comparisons', sa.Column('earlier_area', sa.Float(), nullable=True))
    op.add_column('comparisons', sa.Column('latest_area', sa.Float(), nullable=True))
    op.add_column('comparisons', sa.Column('area_change_percent', sa.Float(), nullable=True))
    op.add_column('comparisons', sa.Column('color_change_metrics', sa.Text(), nullable=True))
    op.add_column('comparisons', sa.Column('shape_change_metrics', sa.Text(), nullable=True))
    op.add_column('comparisons', sa.Column('boundary_change_metrics', sa.Text(), nullable=True))
    op.add_column('comparisons', sa.Column('position_change_metrics', sa.Text(), nullable=True))
    op.add_column('comparisons', sa.Column('measurement_status', sa.String(length=50), nullable=False))
    op.add_column('comparisons', sa.Column('reliability_score', sa.Float(), nullable=True))
    op.add_column('comparisons', sa.Column('uncertainty_reasons', sa.Text(), nullable=True))
    op.add_column('comparisons', sa.Column('observable_metrics', sa.Text(), nullable=True))
    op.add_column('comparisons', sa.Column('comparison_version', sa.String(length=50), nullable=False))
    op.add_column('comparisons', sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comparisons', 'analyzed_at')
    op.drop_column('comparisons', 'comparison_version')
    op.drop_column('comparisons', 'observable_metrics')
    op.drop_column('comparisons', 'uncertainty_reasons')
    op.drop_column('comparisons', 'reliability_score')
    op.drop_column('comparisons', 'measurement_status')
    op.drop_column('comparisons', 'position_change_metrics')
    op.drop_column('comparisons', 'boundary_change_metrics')
    op.drop_column('comparisons', 'shape_change_metrics')
    op.drop_column('comparisons', 'color_change_metrics')
    op.drop_column('comparisons', 'area_change_percent')
    op.drop_column('comparisons', 'latest_area')
    op.drop_column('comparisons', 'earlier_area')
    op.drop_column('comparisons', 'segmentation_error_code')
    op.drop_column('comparisons', 'segmentation_model_version')
    op.drop_column('comparisons', 'segmentation_model')
    op.drop_column('comparisons', 'localization_confidence')
    op.drop_column('comparisons', 'localization_status')
    op.drop_column('comparisons', 'alignment_error_code')
    op.drop_column('comparisons', 'alignment_method')
    op.drop_column('comparisons', 'inlier_ratio')
    op.drop_column('comparisons', 'inlier_count')
    op.drop_column('comparisons', 'match_count')
    op.drop_column('comparisons', 'alignment_score')
    op.drop_column('comparisons', 'processing_error_code')
    op.drop_column('comparisons', 'processing_status')
    # ### end Alembic commands ###
