"""add_ai_explanation_column

Revision ID: 8f66f0090ecf
Revises: 765be5ecfe7b
Create Date: 2026-09-18 18:09:55.458186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f66f0090ecf'
down_revision: Union[str, Sequence[str], None] = '765be5ecfe7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparisons', sa.Column('ai_explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comparisons', 'ai_explanation')
    # ### end Alembic commands ###
