"""Add capture quality assessment fields

Revision ID: ad4cb0027bd9
Revises: 3707d49db3c9
Create Date: 2026-09-18 13:32:51.925068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4cb0027bd9'
down_revision: Union[str, Sequence[str], None] = '3707d49db3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('captures', sa.Column('blur_status', sa.String(length=50), nullable=True))
    op.add_column('captures', sa.Column('lighting_status', sa.String(length=50), nullable=True))
    op.add_column('captures', sa.Column('resolution_status', sa.String(length=50), nullable=True))
    op.add_column('captures', sa.Column('framing_status', sa.String(length=50), nullable=True))
    op.add_column('captures', sa.Column('comparison_eligible', sa.Boolean(), nullable=False))
    op.add_column('captures', sa.Column('quality_details', sa.Text(), nullable=True))
    op.add_column('captures', sa.Column('quality_analyzed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('captures', 'quality_analyzed_at')
    op.drop_column('captures', 'quality_details')
    op.drop_column('captures', 'comparison_eligible')
    op.drop_column('captures', 'framing_status')
    op.drop_column('captures', 'resolution_status')
    op.drop_column('captures', 'lighting_status')
    op.drop_column('captures', 'blur_status')
    # ### end Alembic commands ###
