import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import '../core/theme.dart';
import '../core/providers/account_provider.dart';
import 'package:geolocator/geolocator.dart';

class PrivacySettingsScreen extends StatelessWidget {
  const PrivacySettingsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Privacy Settings', style: GoogleFonts.outfit(fontWeight: FontWeight.bold)),
        leading: const BackButton(),
      ),
      body: ListView(
        padding: const EdgeInsets.all(20),
        children: [
          // ── Image Privacy ─────────────────────────────────────────────────────
          _sectionLabel('IMAGE PRIVACY'),
          const SizedBox(height: 10),
          _infoCard(
            icon: Icons.image_outlined,
            title: 'Private Image Storage',
            status: 'Active',
            statusColor: const Color(0xFF16A34A),
            description:
                'Your SkinTwin captures are stored on the backend server and accessed only '
                'via authenticated requests. Each image is served with ownership verification — '
                'only you can access your captures.',
          ),
          const SizedBox(height: 12),
          _warningCard(
            'Images are stored on the server, not locally on your device. '
            'Server backups may retain data for operational purposes. '
            'Deleting a capture removes the server-side file.',
          ),
          const SizedBox(height: 24),

          // ── Location ──────────────────────────────────────────────────────────
          _sectionLabel('LOCATION'),
          const SizedBox(height: 10),
          _LocationStatusCard(),
          const SizedBox(height: 12),
          _infoCard(
            icon: Icons.location_off_outlined,
            title: 'Location Usage',
            status: 'Find Care Only',
            statusColor: const Color(0xFF2563EB),
            description:
                'Your location is used only when you tap "Use My Location" in Find Care. '
                'It is not tracked continuously, not stored on the server, '
                'and not shared with healthcare providers or third parties.',
          ),
          const SizedBox(height: 24),

          // ── Data Sharing ──────────────────────────────────────────────────────
          _sectionLabel('DATA SHARING'),
          const SizedBox(height: 10),
          _infoCard(
            icon: Icons.share_outlined,
            title: 'Automatic Data Sharing',
            status: 'None',
            statusColor: const Color(0xFF16A34A),
            description:
                'SkinTwin does not automatically share your images, AI explanations, '
                'or personal information with third parties. '
                'Find Care provider discovery does not transmit SkinTwin data.',
          ),
          const SizedBox(height: 12),
          _infoCard(
            icon: Icons.smart_toy_outlined,
            title: 'AI Processing',
            status: 'Local Backend',
            statusColor: const Color(0xFF2563EB),
            description:
                'AI explanations are generated by the backend using the OpenAI API. '
                'Capture images and comparison data are sent to the backend for processing. '
                'Review the backend privacy documentation for details on AI provider data handling.',
          ),
          const SizedBox(height: 24),

          // ── Data Export ───────────────────────────────────────────────────────
          _sectionLabel('YOUR DATA'),
          const SizedBox(height: 10),
          Container(
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: AppTheme.borderColor),
            ),
            child: Column(
              children: [
                _actionTile(
                  icon: Icons.download_outlined,
                  title: 'Export My Data',
                  subtitle: 'Download your profile, SkinTwins, and capture metadata as JSON',
                  onTap: () => _exportData(context),
                ),
                const Divider(height: 1, color: AppTheme.borderColor),
                _actionTile(
                  icon: Icons.delete_outline,
                  title: 'Delete Account & Data',
                  subtitle: 'Permanently remove your account and all associated data',
                  iconColor: const Color(0xFFDC2626),
                  titleColor: const Color(0xFFDC2626),
                  onTap: () => Navigator.pushNamed(context, '/settings'),
                ),
              ],
            ),
          ),
          const SizedBox(height: 24),

          // ── Known Limitations ─────────────────────────────────────────────────
          _sectionLabel('KNOWN LIMITATIONS'),
          const SizedBox(height: 10),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: const Color(0xFFFFFBEB),
              borderRadius: BorderRadius.circular(14),
              border: Border.all(color: const Color(0xFFFDE68A)),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    const Icon(Icons.warning_amber_outlined, color: Color(0xFFB45309), size: 18),
                    const SizedBox(width: 8),
                    Text(
                      'Current Limitations',
                      style: GoogleFonts.inter(
                        fontWeight: FontWeight.w700,
                        fontSize: 13,
                        color: const Color(0xFF92400E),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 10),
                ..._limitations().map(
                  (item) => Padding(
                    padding: const EdgeInsets.only(bottom: 6),
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text('• ', style: TextStyle(color: Color(0xFF92400E))),
                        Expanded(
                          child: Text(
                            item,
                            style: GoogleFonts.inter(fontSize: 12, color: const Color(0xFF92400E)),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 32),
        ],
      ),
    );
  }

  List<String> _limitations() => [
        'Logout clears the token from this device only. The server-side JWT remains valid until it expires (up to 30 minutes).',
        'Data export includes profile metadata, SkinTwins, and capture metadata. Raw image files are not included in the export.',
        'If image file deletion fails during account deletion, the storage file may be orphaned. The database record is still removed.',
        'Biometric app lock is not implemented in this version.',
        'Sharing permissions exist in the data model but sharing features are not yet implemented in the UI.',
        'This system has not undergone a formal third-party security audit.',
      ];

  Future<void> _exportData(BuildContext context) async {
    final account = context.read<AccountProvider>();
    final export = await account.exportData();

    if (!context.mounted) return;

    if (export != null) {
      showDialog(
        context: context,
        builder: (_) => AlertDialog(
          title: Text('Data Export', style: GoogleFonts.outfit(fontWeight: FontWeight.bold)),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Export summary as of ${_formatDate(export.exportedAt)}:',
                style: GoogleFonts.inter(fontSize: 13, color: AppTheme.textMuted),
              ),
              const SizedBox(height: 12),
              _exportRow('SkinTwins', '${export.totalSkinTwins}'),
              _exportRow('Captures', '${export.totalCaptures}'),
              const SizedBox(height: 12),
              Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: const Color(0xFFF0FDF4),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Text(
                  export.exportNotes.first,
                  style: GoogleFonts.inter(fontSize: 12, color: const Color(0xFF166534)),
                ),
              ),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Close'),
            ),
          ],
        ),
      );
    } else if (account.errorMessage != null) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(account.errorMessage!)),
      );
    }
  }

  Widget _exportRow(String label, String value) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 4),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: GoogleFonts.inter(fontSize: 14)),
          Text(value,
              style: GoogleFonts.inter(fontWeight: FontWeight.bold, fontSize: 14)),
        ],
      ),
    );
  }

  String _formatDate(DateTime dt) {
    return '${dt.year}-${dt.month.toString().padLeft(2, '0')}-${dt.day.toString().padLeft(2, '0')} '
        '${dt.hour.toString().padLeft(2, '0')}:${dt.minute.toString().padLeft(2, '0')} UTC';
  }

  // ─── Shared Widgets ──────────────────────────────────────────────────────────

  Widget _sectionLabel(String label) {
    return Text(
      label,
      style: GoogleFonts.inter(
        fontSize: 12,
        fontWeight: FontWeight.bold,
        color: AppTheme.textMuted,
        letterSpacing: 1.2,
      ),
    );
  }

  Widget _infoCard({
    required IconData icon,
    required String title,
    required String status,
    required Color statusColor,
    required String description,
  }) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: AppTheme.borderColor),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(icon, color: AppTheme.primaryBlue, size: 20),
              const SizedBox(width: 10),
              Expanded(
                child: Text(
                  title,
                  style: GoogleFonts.inter(fontWeight: FontWeight.w600, fontSize: 14),
                ),
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                decoration: BoxDecoration(
                  color: statusColor.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Text(
                  status,
                  style: GoogleFonts.inter(
                    fontSize: 11,
                    fontWeight: FontWeight.w600,
                    color: statusColor,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 10),
          Text(
            description,
            style: GoogleFonts.inter(fontSize: 13, color: AppTheme.textMuted, height: 1.5),
          ),
        ],
      ),
    );
  }

  Widget _warningCard(String text) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: const Color(0xFFFFF7ED),
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: const Color(0xFFFED7AA)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Icon(Icons.info_outline, size: 16, color: Color(0xFFEA580C)),
          const SizedBox(width: 8),
          Expanded(
            child: Text(
              text,
              style: GoogleFonts.inter(fontSize: 12, color: const Color(0xFF9A3412)),
            ),
          ),
        ],
      ),
    );
  }

  Widget _actionTile({
    required IconData icon,
    required String title,
    required String subtitle,
    required VoidCallback onTap,
    Color? iconColor,
    Color? titleColor,
  }) {
    return ListTile(
      leading: Icon(icon, color: iconColor ?? AppTheme.primaryBlue),
      title: Text(
        title,
        style: GoogleFonts.inter(
          fontWeight: FontWeight.w600,
          fontSize: 14,
          color: titleColor ?? AppTheme.textDark,
        ),
      ),
      subtitle: Text(subtitle, style: GoogleFonts.inter(fontSize: 12, color: AppTheme.textMuted)),
      trailing: const Icon(Icons.arrow_forward_ios, size: 14, color: AppTheme.textMuted),
      onTap: onTap,
    );
  }
}

// ─── Location Permission Status Card ───────────────────────────────────────────

class _LocationStatusCard extends StatefulWidget {
  @override
  State<_LocationStatusCard> createState() => _LocationStatusCardState();
}

class _LocationStatusCardState extends State<_LocationStatusCard> {
  LocationPermission _permission = LocationPermission.denied;
  bool _loaded = false;

  @override
  void initState() {
    super.initState();
    _checkPermission();
  }

  Future<void> _checkPermission() async {
    final perm = await Geolocator.checkPermission();
    if (mounted) setState(() { _permission = perm; _loaded = true; });
  }

  @override
  Widget build(BuildContext context) {
    if (!_loaded) return const SizedBox.shrink();

    final (label, color) = switch (_permission) {
      LocationPermission.always => ('Always — Consider changing to While In Use', const Color(0xFFB45309)),
      LocationPermission.whileInUse => ('While In Use', const Color(0xFF16A34A)),
      LocationPermission.denied => ('Denied — Find Care will use manual entry', const Color(0xFF6B7280)),
      LocationPermission.deniedForever => ('Denied Permanently — Open Settings to change', const Color(0xFFDC2626)),
      _ => ('Unknown', const Color(0xFF6B7280)),
    };

    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.06),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: color.withValues(alpha: 0.3)),
      ),
      child: Row(
        children: [
          Icon(Icons.my_location_outlined, color: color, size: 18),
          const SizedBox(width: 10),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Location Permission',
                  style: GoogleFonts.inter(fontWeight: FontWeight.w600, fontSize: 13),
                ),
                const SizedBox(height: 2),
                Text(label, style: GoogleFonts.inter(fontSize: 12, color: color)),
              ],
            ),
          ),
          IconButton(
            icon: const Icon(Icons.refresh, size: 18),
            onPressed: _checkPermission,
            tooltip: 'Refresh',
          ),
        ],
      ),
    );
  }
}
